name: "Q Venture Partners"
description: "QVP Website"

url: "http://qventurepartners.com"

paginate: 5
paginate_path: "blog/page:num/"
markdown: rdiscount
permalink: pretty
highlighter: pygments
gems:
    - jekyll-redirect-from
